-- Q01: Tổng số hồ sơ
SELECT COUNT(*) AS TOTAL_ROWS FROM CARDIO_TRAIN;

-- Q02: Số người mắc bệnh
SELECT COUNT(*) AS DISEASE_CASES FROM CARDIO_TRAIN WHERE CARDIO=1;

-- Q03: Số người theo giới tính
SELECT GENDER, COUNT(*) AS PEOPLE FROM CARDIO_TRAIN GROUP BY GENDER ORDER BY GENDER;

-- Q04: 10 người có AP_HI cao nhất
SELECT ID, AP_HI, CARDIO FROM CARDIO_TRAIN ORDER BY AP_HI DESC, ID ASC LIMIT 10;

-- Q05: 10 người có cân nặng trên trung bình
SELECT ID, WEIGHT, CARDIO FROM CARDIO_TRAIN WHERE WEIGHT>(SELECT AVG(WEIGHT) FROM CARDIO_TRAIN) ORDER BY WEIGHT DESC, ID ASC LIMIT 10;

-- Q06: 10 người có đường huyết cao
SELECT ID, GLUC, CARDIO FROM CARDIO_TRAIN WHERE GLUC>1 ORDER BY ID ASC LIMIT 10;

-- Q07: 10 người lớn tuổi nhất
SELECT ID, CAST(AGE/365 AS INTEGER) AS AGE_YEARS, CARDIO FROM CARDIO_TRAIN ORDER BY AGE DESC, ID ASC LIMIT 10;

-- Q08: 10 người có cholesterol mức 3
SELECT ID, CHOLESTEROL, CARDIO FROM CARDIO_TRAIN WHERE CHOLESTEROL=3 ORDER BY ID ASC LIMIT 10;

-- Q09: 10 người hút thuốc
SELECT ID, SMOKE, CARDIO FROM CARDIO_TRAIN WHERE SMOKE=1 ORDER BY ID ASC LIMIT 10;

-- Q10: 10 người có vận động
SELECT ID, ACTIVE, CARDIO FROM CARDIO_TRAIN WHERE ACTIVE=1 ORDER BY ID ASC LIMIT 10;

-- Q11: 10 người có AP_LO thấp nhất
SELECT ID, AP_LO, CARDIO FROM CARDIO_TRAIN ORDER BY AP_LO ASC, ID ASC LIMIT 10;

-- Q12: 10 người uống rượu
SELECT ID, ALCO, CARDIO FROM CARDIO_TRAIN WHERE ALCO=1 ORDER BY ID ASC LIMIT 10;

-- Q13: Xem dữ liệu và đổi tuổi sang năm
SELECT ID, AGE AS AGE_DAYS, CAST(AGE/365 AS INTEGER) AS AGE_YEARS, GENDER, CARDIO FROM CARDIO_TRAIN ORDER BY ID ASC LIMIT 10;
